name: Recent Activity

on:
  schedule:
    - cron: '0 * * * *' # 매 시간마다
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Recent Activity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Readme-Workflows/recent-activity@v1
        with:
          GH_TOKEN: ${{ secrets.RECENT_ACTIVITY_TOKEN }}
